---
title: "T-loggers NKP"
author: "Florian Van Hecke"
date: "2025-01-06"
output: html_document
---
```{r}
library(readxl)
library(ggplot2)
library(scales)
library(tidyr)
library(dplyr)
library(ggpubr)
```

# lees data in
```{r}
# RANDZONE 
## Export 1 (31/10/2024 - 22/01/2024)
data_log1 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 1 2024-01-22 13_57_49 CET (Data CET).xlsx")
data_log2 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 2 2024-01-22 14_00_31 CET (Data CET).xlsx")
data_log3 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 3 2024-01-22 14_02_32 CET (Data CET).xlsx")
data_log4 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 4 2024-01-22 14_04_25 CET (Data CET).xlsx")
data_log5 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 5 2024-01-22 14_06_23 CET (Data CET).xlsx")
data_log6 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 6 2024-01-22 14_07_49 CET (Data CET).xlsx")
data_log7 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 7 2024-01-22 14_12_04 CET (Data CET).xlsx")
data_log8 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 8 2024-01-22 14_14_09 CET (Data CET).xlsx")

summary(data_log1)
colnames(data_log1) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log1$label <- "01"
colnames(data_log2) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log2$label <- "02"
colnames(data_log3) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log3$label <- "03"
colnames(data_log4) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log4$label <- "04"
colnames(data_log5) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log5$label <- "05"
colnames(data_log6) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log6$label <- "06"
colnames(data_log7) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log7$label <- "07"
colnames(data_log8) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log8$label <- "08"

## Export 2 (31/10/2023 - 22/04/2024)
data2_log1 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 1 2024-04-22 12_01_57 CEST (Data CEST).xlsx")
data2_log2 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 2 2024-04-22 12_03_39 CEST (Data CEST).xlsx")
data2_log3 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 3 2024-04-22 12_04_31 CEST (Data CEST).xlsx")
data2_log4 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 4 2024-04-22 12_05_14 CEST (Data CEST).xlsx")
data2_log5 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 5 2024-04-22 12_05_56 CEST (Data CEST).xlsx")
data2_log6 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 6 2024-04-22 12_06_45 CEST (Data CEST).xlsx")
data2_log7 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 7 2024-04-22 12_07_32 CEST (Data CEST).xlsx")
data2_log8 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 8 2024-04-22 12_08_19 CEST (Data CEST).xlsx")

colnames(data2_log1) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log1$label <- "01"
colnames(data2_log2) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log2$label <- "02"
colnames(data2_log3) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log3$label <- "03"
colnames(data2_log4) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log4$label <- "04"
colnames(data2_log5) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log5$label <- "05"
colnames(data2_log6) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log6$label <- "06"
colnames(data2_log7) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log7$label <- "07"
colnames(data2_log8) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log8$label <- "08"

# ZONNEPANELEN

## Export 1 (31/10/2023 - 22/01/2024)
data_log12 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 12 2024-01-22 15_55_07 CET (Data CET).xlsx")
data_log13 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 13 2024-01-22 15_56_24 CET (Data CET).xlsx")
data_log14 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 14 2024-01-22 15_57_27 CET (Data CET).xlsx")
data_log15 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 15 2024-01-22 15_59_20 CET (Data CET).xlsx")
data_log16 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 16 2024-01-22 16_01_12 CET (Data CET).xlsx")
data_log17 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 17 2024-01-22 16_02_04 CET (Data CET).xlsx")
data_log18 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 18 2024-01-22 16_03_20 CET (Data CET).xlsx")
data_log19 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 19 2024-01-22 16_05_14 CET (Data CET).xlsx")
data_log20 <- read_xlsx("./data/Hobo datalog export 1/NKP LOG 20 2024-01-22 16_06_04 CET (Data CET).xlsx")

colnames(data_log12) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log12$label <- "12"
colnames(data_log13) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log13$label <- "13"
colnames(data_log14) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log14$label <- "14"
colnames(data_log15) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log15$label <- "15"
colnames(data_log16) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log16$label <- "16"
colnames(data_log17) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log17$label <- "17"
colnames(data_log18) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log18$label <- "18"
colnames(data_log19) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log19$label <- "19"
colnames(data_log20) <- c("#", "Datum_Tijdstip", "°C", "lux")
data_log20$label <- "20"

## Export 2 (31/10/2023 - 22/04/2024)
data2_log12 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 12 2024-04-22 12_12_11 CEST (Data CEST).xlsx")
data2_log13 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 13 2024-04-22 12_12_59 CEST (Data CEST).xlsx")
data2_log14 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 14 2024-04-22 12_14_29 CEST (Data CEST).xlsx")
data2_log15 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 15 2024-04-22 12_15_59 CEST (Data CEST).xlsx")
data2_log16 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 16 2024-04-22 12_16_57 CEST (Data CEST).xlsx")
data2_log17 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 17 2024-04-22 12_18_03 CEST (Data CEST).xlsx")
data2_log18 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 18 2024-04-22 12_18_47 CEST (Data CEST).xlsx")
data2_log19 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 19 2024-04-22 12_19_31 CEST (Data CEST).xlsx")
data2_log20 <- read_xlsx("./data/Hobo datalog export 2/NKP LOG 20 2024-04-22 12_20_18 CEST (Data CEST).xlsx")

colnames(data2_log12) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log12$label <- "12"
colnames(data2_log13) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log13$label <- "13"
colnames(data2_log14) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log14$label <- "14"
colnames(data2_log15) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log15$label <- "15"
colnames(data2_log16) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log16$label <- "16"
colnames(data2_log17) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log17$label <- "17"
colnames(data2_log18) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log18$label <- "18"
colnames(data2_log19) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log19$label <- "19"
colnames(data2_log20) <- c("#", "Datum_Tijdstip", "°C", "lux")
data2_log20$label <- "20"

## Export 3 (31/10/2023 - 22/08/2024)
data3_log12 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 11 2024-11-20 09_54_11 CET (Data CET).xlsx")
data3_log13 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 12 2024-11-20 09_48_50 CET (Data CET).xlsx")
data3_log14 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 13 2024-11-20 09_49_51 CET (Data CET).xlsx")
data3_log15 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 15 2024-11-20 09_41_13 CET (Data CET).xlsx")
data3_log16 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 16 2024-11-20 10_15_57 CET (Data CET).xlsx")
data3_log17 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 17 2024-11-20 10_24_12 CET (Data CET).xlsx")
data3_log18 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 18 2024-11-20 10_20_43 CET (Data CET).xlsx")
data3_log19 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 19 2024-11-20 10_05_57 CET (Data CET).xlsx")
data3_log20 <- read_xlsx("./data/Hobo datalog export 3/NKP LOG 20 2024-11-20 10_11_11 CET (Data CET).xlsx")

colnames(data3_log12) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log12$label <- "12"
colnames(data3_log13) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log13$label <- "13"
colnames(data3_log14) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log14$label <- "14"
colnames(data3_log15) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log15$label <- "15"
colnames(data3_log16) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log16$label <- "16"
colnames(data3_log17) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log17$label <- "17"
colnames(data3_log18) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log18$label <- "18"
colnames(data3_log19) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log19$label <- "19"
colnames(data3_log20) <- c("#", "Datum_Tijdstip", "°C", "lux")
data3_log20$label <- "20"

reeks_randzone <- c("01", "02", "03", "04", "05", "06", "07", "08")
reeks_zonnepanelen <- c("12", "13", "14", "15", "16", "17", "18", "19", "20")
```

# data samenvoegen en naar wide format
## Randzone (logger 1 - 8)
```{r}
# Export 1
combotabel_RZ <- rbind(data_log1, data_log2, data_log3, data_log4, data_log5, data_log6, data_log7, data_log8)
colnames(combotabel_RZ) <- c("#", "Tijdstip", "Temperatuur", "Helderheid", "Logger")
combo_long_RZ <- combotabel_RZ %>% pivot_longer(cols = c("Temperatuur", "Helderheid"),names_to = "Variabele", values_to = "Meetwaarde")

## add label
combo_long_RZ <- combo_long_RZ %>%
  mutate(
    Eenheid = case_when(
      grepl("Temperatuur", Variabele) ~ "°C",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "lux",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ),Label = case_when(
      grepl("Temperatuur", Variabele) ~ "Temperatuur (°C)",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "Helderheid (lux)",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ))

# Export 2
combotabel2_RZ <- rbind(data2_log1, data2_log2, data2_log3, data2_log4, data2_log5, data2_log6, data2_log7, data2_log8)
colnames(combotabel2_RZ) <- c("#", "Tijdstip", "Temperatuur", "Helderheid", "Logger")
combo2_long_RZ <- combotabel2_RZ %>% pivot_longer(cols = c("Temperatuur", "Helderheid"),names_to = "Variabele", values_to = "Meetwaarde")

## add label
combo2_long_RZ <- combo2_long_RZ %>%
  mutate(
    Eenheid = case_when(
      grepl("Temperatuur", Variabele) ~ "°C",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "lux",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ),Label = case_when(
      grepl("Temperatuur", Variabele) ~ "Temperatuur (°C)",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "Helderheid (lux)",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ))

```

## Zonnepanelen (logger 12 - 20)
```{r}
# Export 1
combotabel_ZP <- rbind(data_log12, data_log13, data_log14, data_log15, data_log16, data_log17, data_log18, data_log19, data_log20)
colnames(combotabel_ZP) <- c("#", "Tijdstip", "Temperatuur", "Helderheid", "Logger")
combo_long_ZP <- combotabel_ZP %>% pivot_longer(cols = c("Temperatuur", "Helderheid"),names_to = "Variabele", values_to = "Meetwaarde")

## add label
combo_long_ZP <- combo_long_ZP %>%
  mutate(
    Eenheid = case_when(
      grepl("Temperatuur", Variabele) ~ "°C",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "lux",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ),Label = case_when(
      grepl("Temperatuur", Variabele) ~ "Temperatuur (°C)",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "Helderheid (lux)",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ))

# Export 2
combotabel2_ZP <- rbind(data2_log12, data2_log13, data2_log14, data2_log15, data2_log16, data2_log17, data2_log18, data2_log19, data2_log20)
colnames(combotabel2_ZP) <- c("#", "Tijdstip", "Temperatuur", "Helderheid", "Logger")
combo2_long_ZP <- combotabel2_ZP %>% pivot_longer(cols = c("Temperatuur", "Helderheid"),names_to = "Variabele", values_to = "Meetwaarde")

## add label
combo2_long_ZP <- combo2_long_ZP %>%
  mutate(
    Eenheid = case_when(
      grepl("Temperatuur", Variabele) ~ "°C",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "lux",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ),Label = case_when(
      grepl("Temperatuur", Variabele) ~ "Temperatuur (°C)",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "Helderheid (lux)",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ))

# Export 3
combotabel3_ZP <- rbind(data3_log12, data3_log13, data3_log14, data3_log15, data3_log16, data3_log17, data3_log18, data3_log19, data3_log20)
colnames(combotabel3_ZP) <- c("#", "Tijdstip", "Temperatuur", "Helderheid", "Logger")
combo3_long_ZP <- combotabel3_ZP %>% pivot_longer(cols = c("Temperatuur", "Helderheid"),names_to = "Variabele", values_to = "Meetwaarde")

## add label
combo3_long_ZP <- combo3_long_ZP %>%
  mutate(
    Eenheid = case_when(
      grepl("Temperatuur", Variabele) ~ "°C",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "lux",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ),Label = case_when(
      grepl("Temperatuur", Variabele) ~ "Temperatuur (°C)",  # If "Variabele" contains "Temperatuur"
      grepl("Helderheid", Variabele) ~ "Helderheid (lux)",  # If "Variabele" contains "Helderheid"
    TRUE ~ NA_character_  # Default case if neither condition matches
  ))
```


# plot
```{r}
# check outliers
ggplot(data_log1,
       aes(x = Datum_Tijdstip, y = `°C`)) +
  geom_boxplot()

# metingen van  logger 1
ggplot(data_log1,
       aes(x = Datum_Tijdstip, y = `°C`)) +
  geom_line(colour = "red") +
  geom_line(data = data_log1, aes(x = Datum_Tijdstip, y = lux)) +
  labs(title = "Temperatuurverloop + helderheid Logger 1 Nieuwkapelleplas") +
  ylab("Meetwaarde (log10)") +
  xlab("Datum staalname") +
  scale_y_log10() + 
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

```

# Randzone logger 1 - 8 
```{r}
# temperatuur (°C)
ggplot(data_log1,
       aes(x = Datum_Tijdstip, y = `°C`)) +
  geom_line(colour = "red") +
  geom_line(data = data_log2, aes(x = Datum_Tijdstip, y = `°C`), colour = "orange") +
  geom_line(data = data_log3, aes(x = Datum_Tijdstip, y = `°C`), colour = "yellow") +
  geom_line(data = data_log4, aes(x = Datum_Tijdstip, y = `°C`), colour = "lightgreen") +
  geom_line(data = data_log5, aes(x = Datum_Tijdstip, y = `°C`), colour = "green") +
  geom_line(data = data_log6, aes(x = Datum_Tijdstip, y = `°C`), colour = "darkgreen") +
  geom_line(data = data_log7, aes(x = Datum_Tijdstip, y = `°C`), colour = "lightblue") +
  geom_line(data = data_log8, aes(x = Datum_Tijdstip, y = `°C`), colour = "blue") +
  labs(title = "Temperatuurverloop Loggers randzone (1-8) Nieuwkapelleplas") +
  ylab("Temperatuur (°C)") +
  xlab("Datum staalname") +
  scale_y_continuous(breaks = seq(0,17,1)) +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

# helderheid (lux)
## geen transformatie lux
ggplot(data_log1,
       aes(x = Datum_Tijdstip, y = lux)) +
  geom_line(colour = "red") +
  geom_line(data = data_log2, aes(x = Datum_Tijdstip, y = lux), colour = "orange") +
  geom_line(data = data_log3, aes(x = Datum_Tijdstip, y = lux), colour = "yellow") +
  geom_line(data = data_log4, aes(x = Datum_Tijdstip, y = lux), colour = "lightgreen") +
  geom_line(data = data_log5, aes(x = Datum_Tijdstip, y = lux), colour = "green") +
  geom_line(data = data_log6, aes(x = Datum_Tijdstip, y = lux), colour = "darkgreen") +
  geom_line(data = data_log7, aes(x = Datum_Tijdstip, y = lux), colour = "lightblue") +
  geom_line(data = data_log8, aes(x = Datum_Tijdstip, y = lux), colour = "blue") +
  labs(title = "Lichtintensiteit Loggers randzone (1-8) Nieuwkapelleplas") +
  ylab("Helderheid (lux)") +
  xlab("Datum staalname") +
  ylim(0,8000) +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

## logaritmische transformatie lux
ggplot(data_log1,
       aes(x = Datum_Tijdstip, y = lux)) +
  geom_line(colour = "red") +
  geom_line(data = data_log2, aes(x = Datum_Tijdstip, y = lux), colour = "orange") +
  geom_line(data = data_log3, aes(x = Datum_Tijdstip, y = lux), colour = "yellow") +
  geom_line(data = data_log4, aes(x = Datum_Tijdstip, y = lux), colour = "lightgreen") +
  geom_line(data = data_log5, aes(x = Datum_Tijdstip, y = lux), colour = "green") +
  geom_line(data = data_log6, aes(x = Datum_Tijdstip, y = lux), colour = "darkgreen") +
  geom_line(data = data_log7, aes(x = Datum_Tijdstip, y = lux), colour = "lightblue") +
  geom_line(data = data_log8, aes(x = Datum_Tijdstip, y = lux), colour = "blue") +
  labs(title = "Lichtintensiteit Loggers randzone (1-8) Nieuwkapelleplas") +
  ylab("Helderheid (lux)") +
  xlab("Datum staalname") +
  ylim(0,8000) +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y")) +
  scale_y_log10()
```


# Zonnepanelen logger 12 - 20
```{r}
# temperatuur (°C)
ggplot(data_log12,
       aes(x = Datum_Tijdstip, y = `°C`)) +
  geom_line(colour = "red") +
  geom_line(data = data_log13, aes(x = Datum_Tijdstip, y = `°C`), colour = "orange") +
  geom_line(data = data_log14, aes(x = Datum_Tijdstip, y = `°C`), colour = "yellow") +
  geom_line(data = data_log15, aes(x = Datum_Tijdstip, y = `°C`), colour = "lightgreen") +
  geom_line(data = data_log16, aes(x = Datum_Tijdstip, y = `°C`), colour = "green") +
  geom_line(data = data_log17, aes(x = Datum_Tijdstip, y = `°C`), colour = "darkgreen") +
  geom_line(data = data_log18, aes(x = Datum_Tijdstip, y = `°C`), colour = "lightblue") +
  geom_line(data = data_log19, aes(x = Datum_Tijdstip, y = `°C`), colour = "blue") +
  geom_line(data = data_log20, aes(x = Datum_Tijdstip, y = `°C`), colour = "darkblue") +
  labs(title = "Temperatuurverloop Loggers zonnepaneelzone (12-20) Nieuwkapelleplas") +
  ylab("Temperatuur (°C)") +
  xlab("Datum staalname") +
  scale_y_continuous(breaks = seq(0,17,1)) +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

# licht-intensiteit (lux)
ggplot(data_log12,
       aes(x = Datum_Tijdstip, y = lux)) +
  geom_line(colour = "red") +
  geom_line(data = data_log13, aes(x = Datum_Tijdstip, y = lux), colour = "orange") +
  geom_line(data = data_log14, aes(x = Datum_Tijdstip, y = lux), colour = "yellow") +
  geom_line(data = data_log15, aes(x = Datum_Tijdstip, y = lux), colour = "lightgreen") +
  geom_line(data = data_log16, aes(x = Datum_Tijdstip, y = lux), colour = "green") +
  geom_line(data = data_log17, aes(x = Datum_Tijdstip, y = lux), colour = "darkgreen") +
  geom_line(data = data_log18, aes(x = Datum_Tijdstip, y = lux), colour = "lightblue") +
  geom_line(data = data_log19, aes(x = Datum_Tijdstip, y = lux), colour = "blue") +
  geom_line(data = data_log20, aes(x = Datum_Tijdstip, y = lux), colour = "darkblue") +
  labs(title = "Lichtintensiteit Loggers zonnepaneelzone (12-20) Nieuwkapelleplas") +
  ylab("Temperatuur (°C)") +
  xlab("Datum staalname") +
  scale_y_log10() +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))
```

# met gecombineerde tabel
```{r}
# data-reeks 1
## Randzone
combo_long_RZ %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

combo_long_RZ %>% filter(Variabele == "Helderheid") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_y_log10() +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

## Zonnepanelen
combo_long_ZP %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

combo_long_ZP %>% filter(Variabele == "Helderheid") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_y_log10() +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

## vergelijking RZ en ZP
### temperatuur
temp_ZP <- combo_long_ZP %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Logger, y = Meetwaarde, colour = Logger)) +
  geom_boxplot() +
  ylab("") +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

temp_RZ <- combo_long_RZ %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Logger, y = Meetwaarde, colour = Logger)) +
  geom_boxplot() +
  ylab("Temperatuur (°C)") +
  scale_x_datetime(breaks = date_breaks("1 week"), labels = date_format("%d-%m-%Y"))

ggarrange(temp_RZ, temp_ZP, ncol = 2, legend = FALSE)

### licht-intensiteit
ggplot() +
  geom_boxplot(data = combo_long_ZP %>% 
                 filter(Variabele == "Helderheid"), aes(x = Logger, y = Meetwaarde, colour = Logger)) + 
  geom_boxplot(data = combo_long_RZ %>% 
                 filter(Variabele == "Helderheid"), aes(x = Logger, y = Meetwaarde, colour = Logger)) +
  ylab("Licht-intensiteit (lux)") +
  scale_y_log10()

# data-reeks 2
## Randzone
combo2_long_RZ %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_x_datetime(breaks = date_breaks("1 month"), labels = date_format("%b-%Y"))

combo2_long_RZ %>% filter(Variabele == "Helderheid") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_y_log10() +
  scale_x_datetime(breaks = date_breaks("1 month"), labels = date_format("%b-%Y"))

## Zonnepanelen
combo2_long_ZP %>% filter(Variabele == "Temperatuur") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_x_datetime(breaks = date_breaks("1 month"), labels = date_format("%b-%Y"))

combo2_long_ZP %>% filter(Variabele == "Helderheid") %>%
  ggplot(aes(x = Tijdstip, y = Meetwaarde, colour = Logger)) +
  geom_line() +
  scale_y_log10() +
  scale_x_datetime(breaks = date_breaks("1 month"), labels = date_format("%b-%Y"))

```

